export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_PRODUCT_PRICE = 'SET_PRODUCT_PRICE';
export const SET_GOODS = 'SET_PRODUCT';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_GOODS_TOTAL_COUNT = 'SET_GOODS_TOTAL_COUNT';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
