// auth
export const SET_AUTH_USER_DATA = 'SET_AUTH_USER_DATA';

// goods
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_GOODS = 'SET_PRODUCT';
export const PRODUCT_DECRIMENT_INCRIMENT = 'PRODUCT_DECRIMENT_INCRIMENT';

export const TOGGLE_ISFETCHING = 'SET_ISFETCHING';

// page
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_GOODS_TOTAL_COUNT = 'SET_GOODS_TOTAL_COUNT';

// basket
export const ADD_PRODUCT_ORDER = 'ADD_PRODUCT_ORDER';
export const UPDATE_PRODUCT_ORDER = 'UPDATE_PRODUCT_ORDER';
export const DELETE_PRODUCT_ORDER = 'DELETE_PRODUCT_ORDER';
export const TOTAL_PRODUCT = 'TOTAL_PRODUCT';
