export const ADD_PRODUCT_ORDER = 'ADD_PRODUCT_ORDER';
export const UPDATE_PRODUCT_ORDER = 'UPDATE_PRODUCT_ORDER';
export const DELETE_PRODUCT_ORDER = 'DELETE_PRODUCT_ORDER';
export const TOTAL_PRODUCT = 'TOTAL_PRODUCT';
